/*
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

//v2
function n12_v2(){
    console.time('timer');
    var triangleNumber, previousNumber, index, counter, maxCount;
    counter = 1;
    previousNumber = 0;
    maxCount = 2;
    for(; index <= 500 ; counter++){
        triangleNumber = previousNumber + counter;

        if(triangleNumber % 2 !== 0 || triangleNumber % 3 !== 0 || triangleNumber % 4 !== 0){
            previousNumber = triangleNumber;
            continue;
        }

        index = 0;
        for(var divider = 1; divider <= triangleNumber; divider++){
            if(triangleNumber % divider === 0){
                index++;
            }
        }

        if (index > maxCount) {
            maxCount = index;
        };

        previousNumber = triangleNumber;
    }

  console.timeEnd('timer');
  return triangleNumber;
}

// timer: 228292.000ms 
// answer: 76576500

//v3
function n12_v3(){
    console.time('timer');

    function divisors(x) {
        var limit = Math.sqrt(x);
        var numberOfDivisors = 0;

        for (var i = 0; i < limit; i++) {
            if (x % i == 0) {
                limit = x / i;
                if (limit != i) {
                    numberOfDivisors++;
                }

                numberOfDivisors++;
            }
        }

      return numberOfDivisors;
    }

    var triangleNumber, previousNumber, index, counter, powIndex;
    previousNumber = 0;
    powIndex = 1/3;
    for(counter = 1; index <= 500 ; counter++){
        triangleNumber = previousNumber + counter;

        if (Math.pow(triangleNumber, powIndex) < 250 || triangleNumber % 2 !== 0 || triangleNumber % 3 !== 0 || triangleNumber % 4 !== 0) {
            previousNumber = triangleNumber;
            continue;
        };

        index = divisors(triangleNumber);
        previousNumber = triangleNumber;
    }

    console.timeEnd('timer');
    return 'answer: ' + triangleNumber;
}

// timer: 339.000ms
// answer: 76576500
